#!/bin/sh
##                               -*- Mode: Sh -*- 
## start-server -- 
## ITIID           : $ITI$ $Header $__Header$
## Author          : Ulrich Pfeifer
## Created On      : Fri Nov 24 13:19:05 1995
## Last Modified By: Ulrich Pfeifer
## Last Modified On: Fri Nov 24 13:19:39 1995
## Language        : sh
## Update Count    : 1
## Status          : Unknown, Use with caution!
## 
## (C) Copyright 1995, Universität Dortmund, all rights reserved.
## 
## $Locker: pfeifer $
## $Log: start-server,v $
## Revision 1.0.1.1  1995/11/24  16:19:55  pfeifer
## patch5: Not very interesting but useful for me ;-)
##
## 

host=`hostname`
if [ "$host" = "schroeder" ] ; then
        echo "Starting math";
        echo "Exit" | \
        math -linkmode listen -linkprotocol TCP -linkname 3000 -mathlink
else
        echo "Starting math on schroeder";
	rsh schroeder "echo Exit | math -linkmode listen -linkprotocol TCP -linkname 3000 -mathlink"
fi

